# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratsightings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratsighting',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ratsighting',
            name='location_type',
            field=models.CharField(max_length=100),
        ),
    ]
