# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 23:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratsightings', '0003_ratsighting_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratsighting',
            options={'ordering': ('date_created',)},
        ),
    ]
