# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 23:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ratsightings', '0004_auto_20171020_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratsighting',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratsightings', to=settings.AUTH_USER_MODEL),
        ),
    ]
