# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-05 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratsightings', '0005_auto_20171020_2323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratsighting',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AlterField(
            model_name='ratsighting',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
